### PR TITLE
Usage of buy app function

### PR DESCRIPTION
**Pull request by MohammedJ18**

### CODE REVIEW

**Review by Gruce — CHANGES_REQUESTED** [review]
Hello @MohammedJ18 ,

Please specify the errors in `useAppManager` and return them.

Thank you.

**Comment by MohammedJ18** [comment]
Hello @Gruce,

I have finished specifying the error message in `useAppManager `.
Thank you.

**Comment by Gruce** [comment]
Please check my comment in #19

**Review by Gruce — APPROVED** [review]
Hello @MohammedJ18 ,
I have approved the pull request, but in the future it needs more specific errors to be showed and controlled by the composables.

Thank you.

**Pull request merged**
